### ISSUE TITLE
Request for datasets and training code

### ISSUE THREAD

**Issue by xxupiano** [sander-wood/text-to-music#1]
Hi,
Thanks for giving the 1st nice try on text-to-music!
Could you please release the dataset Textune and training code?
Sincerely

**Comment by sander-wood** [comment]
Hi Xin,
Thank you for your interest in this project! The dataset Textune was collected internally and there are no plans to release it for now. However, Textune will probably be released under some form in the future. If interested in this dataset, please stay tuned for further updates.

**Comment by xxupiano** [comment]
Thanks for your reply.
